### ISSUE TITLE
[v0.0.7] LocalAI - Please add Datasource ability

### ISSUE THREAD

**Issue by Moep90** [trypromptly/LLMStack#27]
**Is your feature request related to a problem? Please describe.**
The "Applet" `text-chat` processor of promtly has the ability to use a Datasource (website, files etc.). However the LocalAI Processor does not. Is this currently possible or does this need to be implemented?
If last, please update the localAI Processor documentation.

**Describe the solution you'd like**
I'd like to have equal behavior between all backends. With LocalAI my company is able to run everything localy (besides websites we want to scrape).

**Comment by ajhai** [comment]
@Moep90 Promptly's text-chat processor is a high level abstraction built on top of OpenAI's ChatGPT whereas LocalAI processors are all parallel to OpenAI's processors. In that sense, LocalAI's chat completions is similar to OpenAI's ChatGPT.

Promptly's text-chat already allows users to pick Azure ChatGPT. We are planning to enhance it to make it work with LocalAI backend too.

Also curious, when you say you are using LocalAI locally, is this together with LLMStack to build apps or just LocalAI alone in isolation?

**Comment by Moep90** [comment]
@ajhai some sort of. We dont have a clear view right now.
1. We want to use it for our collegues and enrich the vector database with our internal informations (thats we want to do it locally)
2. We want to create specific chatbots for certain products etc.
3. ....tbd...

**Comment by ajhai** [comment]
@Moep90 we are working towards running everything off of LocalAI including embedding generations etc. One of the next few releases should contain these changes.

**Comment by jimiopex** [comment]
Hey @ajhai 
This LLMStack platform is awesome!, We are looking forward to trial text-chat processor with Local-AI, Any approximate timeline for the release?

Cheers!
Jim

**Comment by ajhai** [comment]
@jimiopex I should have these changes out later today. Will update this thread.

**Comment by Moep90** [comment]
> @jimiopex I should have these changes out later today. Will update this thread.

Any update here?

**Comment by ajhai** [comment]
We have now added LocalAI support to `TextChat` processor. Configure LocalAI base url and api key and check the `Use LocalAI if available` check box in TextChat processor's advanced configuration.

<img width="515" alt="image" src="https://github.com/trypromptly/LLMStack/assets/431988/ba53dbce-8c57-4c71-b7d0-6f8fdde8071d">

**Comment by jimiopex** [comment]
@ajhai I have marked LocalAIand also configured Key & base url, Still it fallbacks to OpenAI, Following is the response

Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))

Please suggest me if I need to do any other configurations or will the textChat processor hit OpenAI anyways?

**Comment by ajhai** [comment]
@jimiopex can you pull the latest release and try again? There was a bug where we were not passing the api_key properly to text chat processor

**Comment by Prasath-M0** [comment]
@ajhai I am unable to see use LocalAI check box in Text chat processor. Attached file for your reference. Please let me know solution for this.
![Screenshot from 2023-09-22 11-18-08](https://github.com/trypromptly/LLMStack/assets/102050731/a8328c1b-3efc-4ce3-8dd7-1401307bd578)

**Comment by ajhai** [comment]
@Prasath-M0 can you update your LLMStack installation? We added this in the latest release.

**Comment by jimiopex** [comment]
@ajhai 
I have pulled the latest code & still facing the same error #1 and if I remove "ID of the model to use" under "Advanced", system throws error #2.

#1 -
 Error communicating with OpenAI: HTTPConnectionPool(host='10.20.125.70', port=80): Max retries exceeded with url: /v1//chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8b172a50>: Failed to establish a new connection: [Errno 111] Connection refused'))

#2 - 
Error starting coordinator: 1 validation error for TextChatConfiguration model none is not an allowed value (type=type_error.none.not_allowed)

Somewhere its still not picking up with LocalAI & trying to be routed via openAI. Please let me know if I am missing something in the configuration.
